/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_VentanaCita;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelica
 */
public class Ventana_Cita extends javax.swing.JFrame{

    /**
     * Creates new form Ventana_Cita
     */
    Controlador_VentanaCita controlador;
    
    public Ventana_Cita() {
        initComponents();
        controlador= new Controlador_VentanaCita(this);
        agregarEventos();
        this.setLocationRelativeTo(null);
        
    }
    
    public void agregarEventos(){
        this.btn_Buscar.addActionListener(controlador);
        this.jcb_Opciones.addActionListener(controlador);
        this.jcb_TipoCliente.addActionListener(controlador);
        this.btn_SiguienteCliente.addActionListener(controlador);
        this.jcb_Reportes.addActionListener(controlador);
        this.btn_MayorAMenor.addActionListener(controlador);
        this.btn_MenorAMayor.addActionListener(controlador);
    }
    
    public String devolverSeleccionComboBoxOpciones() {
        String ordenSeleccionado = "";
        if (this.jcb_Opciones.getSelectedItem().toString().equals("Agregar Cita")) {
            ordenSeleccionado = "Agregar";
        }
        if (this.jcb_Opciones.getSelectedItem().toString().equals("Modificar Cita")) {
            ordenSeleccionado = "Modificar";
        }
        if (this.jcb_Opciones.getSelectedItem().toString().equals("Cancelar Cita")) {
            ordenSeleccionado = "Cancelar";
        }
        if (this.jcb_Opciones.getSelectedItem().toString().equals("Reportes")) {
            ordenSeleccionado = "Reportes";
        }
        return ordenSeleccionado;
    }
    
     public String devolverSeleccionComboBox() {
        String ordenSeleccionado = "";
        if (this.jcb_Reportes.getSelectedItem().toString().equals("Mostrar todas las citas")) {
            ordenSeleccionado = "Toda la lista";
        }
        if (this.jcb_Reportes.getSelectedItem().toString().equals("Mostrar promedio de edades")) {
            ordenSeleccionado = "Promedio de edades";
        }
        if (this.jcb_Reportes.getSelectedItem().toString().equals("Mostrar cantidad de citas")) {
            ordenSeleccionado = "Cantidad de citas";
        }
        return ordenSeleccionado;
    }
    
    public void limpiarArea() {
        this.jta_Reportes.setText("");
    }
    
    public void imprimirEnElArea(String texto) {
        this.jta_Reportes.setText(texto);
    }
    
    public String devolverSeleccionTipoCliente() {
        String ordenSeleccionado = "";
        if (this.jcb_TipoCliente.getSelectedItem().toString().equals("Regular")) {
            ordenSeleccionado = "Regular";
        }
        if (this.jcb_TipoCliente.getSelectedItem().toString().equals("Preferencial (7600)")) {
            ordenSeleccionado = "Preferencial";
        }
        return ordenSeleccionado;
    }
    
    public void limpiarInterfaz() {
        jt_Cedula.setText("");
        jt_Edad.setText("");
        jt_Nombre.setText("");
        jt_FechaCita.setText("");
    }
    
    public void llenarInterfaz(String nombre, String edad, String fechaCita){
        this.jt_Nombre.setText(nombre);
        this.jt_Edad.setText(edad);
        this.jt_FechaCita.setText(fechaCita);
    }
    
    public String getCedula() {
        return this.jt_Cedula.getText().trim();
    }
    
    public String getNombre() {
        return this.jt_Nombre.getText().trim();
    }
    
    public String getEdad() {
        return this.jt_Edad.getText().trim();
    }
    
    public String getFechaCita() {
        return this.jt_FechaCita.getText().trim();
    }
    
    public String[] devolverDatosModificar() {
        String arreglo[] = new String[3];
        arreglo[0] = this.jt_Nombre.getText().trim();
        arreglo[1] = this.jt_Edad.getText().trim();
        arreglo[1] = this.jt_FechaCita.getText().trim();
        return arreglo;
    }
    
    public void deshabilitarCedula(){
        this.jt_Cedula.disable();
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jt_FechaCita = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jcb_Opciones = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcb_TipoCliente = new javax.swing.JComboBox<>();
        btn_SiguienteCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Reportes = new javax.swing.JTextArea();
        jcb_Reportes = new javax.swing.JComboBox<>();
        btn_MenorAMayor = new javax.swing.JButton();
        btn_MayorAMenor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Citas Migracion");

        jLabel5.setText("Fecha Cita:");

        btn_Buscar.setText("Buscar");

        jcb_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar Cita", "Modificar Cita", "Cancelar Cita" }));
        jcb_Opciones.setActionCommand("Opciones");

        jLabel6.setText("Tipo Cliente:");

        jcb_TipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Preferencial (7600)" }));
        jcb_TipoCliente.setActionCommand("Tipo Cliente");

        btn_SiguienteCliente.setText("Atender Siguiente Cliente");

        jta_Reportes.setColumns(20);
        jta_Reportes.setRows(5);
        jScrollPane1.setViewportView(jta_Reportes);

        jcb_Reportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todas las citas", "Mostrar promedio de edades", "Mostrar cantidad de citas" }));
        jcb_Reportes.setActionCommand("Reportes");

        btn_MenorAMayor.setText("Ordenar Menor a Mayor");

        btn_MayorAMenor.setText("Ordenar Mayor a Menor");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_SiguienteCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel1))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_FechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Buscar))
                                .addComponent(jt_Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_TipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_MayorAMenor)
                                .addGap(52, 52, 52)
                                .addComponent(btn_MenorAMayor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcb_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jt_FechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcb_TipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcb_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_MayorAMenor)
                            .addComponent(btn_MenorAMayor)
                            .addComponent(btn_SiguienteCliente))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_MayorAMenor;
    private javax.swing.JButton btn_MenorAMayor;
    private javax.swing.JButton btn_SiguienteCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_Opciones;
    private javax.swing.JComboBox<String> jcb_Reportes;
    private javax.swing.JComboBox<String> jcb_TipoCliente;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_FechaCita;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextArea jta_Reportes;
    // End of variables declaration//GEN-END:variables
}
